syntax = "proto3";

package proto.packet;

message Uuid {
	// The high 64 bits of the UUID.
	uint64 hi = 1;
	// The low 64 bits of the UUID.
	uint64 lo = 2;
}

message Host_DownloadListedModel {
	Uuid model_id = 1;
	Uuid job_id = 2;
}

message JobStatusDownloading {}
message JobStatusComplete {}
message JobStatusError {
	string error = 1;
}

message Worker_JobStatusResponse {
	Uuid job_id = 1;
	uint64 total_size = 2;
	uint64 downloaded_size = 3;
	oneof status {
		JobStatusDownloading downloading = 4;
		JobStatusComplete complete = 5;
		JobStatusError error = 6;
	}
}

message Host_GetDownloadableModelsList {}

message Model {
	string name = 1;
	uint64 size = 2;
	string type = 3;
	Uuid id = 4;
}

message Worker_GetDownloadableModelsListResponse {
	repeated Model models = 1;
}

message Host_GetAvailableModelsList {}

message Worker_GetAvailableModelsListResponse {
	repeated Model models = 1;
}

message Host_KillWorker {}

message HostPacket {
	oneof contents {
		Host_GetDownloadableModelsList dl_models_list = 1;
		Host_DownloadListedModel dl_listed_model = 2;
		Host_KillWorker kill = 3;
		Host_GetAvailableModelsList models_list = 4;
	}
}

message WorkerPacket {
	oneof contents {
		Worker_GetDownloadableModelsListResponse dl_models_list_response = 1; 
		Worker_JobStatusResponse job_status_response = 2;
		Worker_GetAvailableModelsListResponse models_list_response = 3;
	}
}