on: [push, pull_request, workflow_dispatch]

name: CI

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  UBUNTU_DEPS: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libasound2-dev libfreetype-dev libfontconfig-dev libopus-dev libx264-dev libvpx-dev nasm autoconf automake build-essential cmake git-core libass-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev meson ninja-build pkg-config texinfo wget yasm zlib1g-dev

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Dependencies (Ubuntu)
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ${{ env.UBUNTU_DEPS }}
          version: 1.0
      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --workspace

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Dependencies (Ubuntu)
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ${{ env.UBUNTU_DEPS }}
          version: 1.0
      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib --features=build-ffmpeg

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Dependencies (Ubuntu)
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ${{ env.UBUNTU_DEPS }}
          version: 1.0
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features=build-ffmpeg -- -D warnings

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          TARGET: aarch64-apple-darwin
          ONNX_URL: https://github.com/microsoft/onnxruntime/releases/download/v1.28.2/onnxruntime-osx-arm64-1.28.2.tgz

        - os: ubuntu-24.04-arm
          TARGET: aarch64-unknown-linux-gnu
          ONNX_URL: https://github.com/microsoft/onnxruntime/releases/download/v1.28.2/onnxruntime-linux-aarch64-1.28.2.tgz

        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-gnu
          ONNX_URL: https://github.com/microsoft/onnxruntime/releases/download/v1.28.2/onnxruntime-linux-x64-gpu_cuda13-1.28.2.tgz

        - os: windows-11-arm
          TARGET: aarch64-pc-windows-msvc
          EXTENSION: .exe
          FFMPEG_URL: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-02-13-13/ffmpeg-n9.0.1-11-ge47273f4d9-winarm64-gpl-shared-9.0.zip
          ONNX_URL: https://github.com/microsoft/onnxruntime/releases/download/v1.28.2/onnxruntime-win-arm64-1.28.2.zip

        - os: windows-latest
          TARGET: x86_64-pc-windows-msvc
          FFMPEG_URL: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-02-13-13/ffmpeg-n9.0.1-11-ge47273f4d9-win64-gpl-shared-9.0.zip
          ONNX_URL: https://github.com/microsoft/onnxruntime/releases/download/v1.28.2/onnxruntime-win-x64-gpu_cuda13-1.28.2.zip
          EXTENSION: .exe
    name: Build ${{ matrix.TARGET }}
    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"

    - uses: actions/checkout@master
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Install Dependencies (MacOS)
      if: contains(matrix.TARGET, 'apple')
      run: |
        brew install automake git lame libass libtool libvorbis libvpx opus sdl shtool texi2html theora wget x264 x265 xvid nasm

    - name: Install Dependencies (Ubuntu)
      uses: awalsh128/cache-apt-pkgs-action@v1
      if: contains(matrix.TARGET, 'linux')
      with:
        packages: ${{ env.UBUNTU_DEPS }}
        version: 1.0

    - name: Cache ffmpeg (Windows)
      if: contains(matrix.TARGET, 'windows')
      id: cache-ffmpeg-windows
      uses: actions/cache@v6
      with:
        path: C:/ffmpeg
        key: ${{ runner.os }}-${{ matrix.TARGET }}-ffmpeg
    - name: Install ffmpeg (Windows)
      shell: pwsh
      if: contains(matrix.TARGET, 'windows') && steps.cache-ffmpeg-windows.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest ${{ matrix.FFMPEG_URL }} -OutFile "$env:Temp\ffmpeg.zip"
        Expand-Archive -Path "$env:Temp\ffmpeg.zip" -DestinationPath C:\ffmpeg
    - name: Set FFMPEG_DIR (Windows)
      shell: pwsh
      if: contains(matrix.TARGET, 'windows')
      run: |
        $path = @(Get-ChildItem -Path C:\ffmpeg)[0]
        echo "FFMPEG_DIR=$path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "$path"
        Get-ChildItem $path

    - name: Cache onnxruntime
      uses: actions/cache@v6
      id: cache-onnxruntime
      with:
        path: /tmp/onnxruntime
        key: ${{ runner.os }}-${{ matrix.TARGET }}-onnx
    - name: Download onnxruntime (Windows)
      if: contains(matrix.TARGET, 'windows') && steps.cache-onnxruntime.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest ${{ matrix.ONNX_URL }} -OutFile "$env:Temp\onnx.zip"
        Expand-Archive -Path "$env:Temp\onnx.zip" -DestinationPath "$env:Temp\onnx"
        mkdir D:\tmp\onnxruntime
        cp "$env:Temp\onnx\*\lib\*.dll" D:\tmp\onnxruntime

    - name: Download onnxruntime
      if: ${{ !contains(matrix.TARGET, 'windows') && steps.cache-onnxruntime.outputs.cache-hit != 'true' }}
      run: |
        wget ${{ matrix.ONNX_URL }}
        tar -xvf onnxruntime-*.tgz
        mkdir /tmp/onnxruntime
        cp onnxruntime*/lib/*.so /tmp/onnxruntime 2> /dev/null || :
        cp onnxruntime*/lib/*.dylib /tmp/onnxruntime 2> /dev/null || :

    - name: Build (Windows)
      if: contains(matrix.TARGET, 'windows')
      shell: pwsh
      run: |
        echo $env:FFMPEG_DIR
        cargo build --verbose --workspace --release --target=${{ matrix.TARGET }}

    - name: Build
      if: ${{ !contains(matrix.TARGET, 'windows') }}
      run: |
        cargo build --verbose --workspace --release --features=build-ffmpeg --target=${{ matrix.TARGET }}

    - name: Make release
      if: ${{ !contains(matrix.TARGET, 'windows') }}
      run: |
        cp target/${{ matrix.TARGET }}/release/ksng${{ matrix.EXTENSION }} "ksng-${{ matrix.TARGET }}${{ matrix.EXTENSION }}"
        cp target/${{ matrix.TARGET }}/release/ksng-ml${{ matrix.EXTENSION }} "/tmp/onnxruntime/ksng-ml${{ matrix.EXTENSION }}"
        mkdir /tmp/onnxbundle
        cp /tmp/onnxruntime/* /tmp/onnxbundle
        cp target/${{ matrix.TARGET }}/release/ksng${{ matrix.EXTENSION }} "/tmp/onnxbundle/ksng-${{ matrix.TARGET }}${{ matrix.EXTENSION }}"

    - name: Make release (Windows)
      if: contains(matrix.TARGET, 'windows')
      shell: pwsh
      run: |
        mkdir /tmp/ffmpeg -Force
        cp target/${{ matrix.TARGET }}/release/ksng${{ matrix.EXTENSION }} "/tmp/ffmpeg/ksng-${{ matrix.TARGET }}${{ matrix.EXTENSION }}"
        cp "$env:FFMPEG_DIR/bin/*.dll" /tmp/ffmpeg
        cp target/${{ matrix.TARGET }}/release/ksng-ml${{ matrix.EXTENSION }} "/tmp/onnxruntime/ksng-ml${{ matrix.EXTENSION }}"
        mkdir /tmp/onnxbundle -Force
        cp /tmp/onnxruntime/* /tmp/onnxbundle
        cp /tmp/ffmpeg/* /tmp/onnxbundle

    - name: Upload artifact
      if: ${{ !contains(matrix.TARGET, 'windows') }}
      uses: actions/upload-artifact@master
      with:
        name: ksng-${{ matrix.TARGET }}
        path: ksng-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

    - name: Upload artifact (Windows)
      if: contains(matrix.TARGET, 'windows')
      uses: actions/upload-artifact@master
      with:
        name: ksng-${{ matrix.TARGET }}
        path: /tmp/ffmpeg
        archive: true

    - name: Upload ksng-ml
      uses: actions/upload-artifact@master
      with:
        name: ksng-ml-${{ matrix.TARGET }}
        archive: true
        path: /tmp/onnxruntime

    - name: Upload bundle
      uses: actions/upload-artifact@master
      with:
        name: ksng-bundle-${{ matrix.TARGET }}
        archive: true
        path: /tmp/onnxbundle